results_dir: "./exp1/"
wandb_opt: False

data_dir:
  block_test: "./data/test.csv"
  block_submission: "./data/sample_submission.csv"


eval:
  trained_model: './exp/train_merge8/daconBlock_8.pth'
  save_dir_name: 'eval_merge8'
  batch_size: 128
  num_workers: 4
  data:
    img_size: 224


