results_dir: "./exp1/"
wandb_opt: False

data_dir:
  block_train: "./data/train.csv"
  block_test: "./data/test.csv"

data:
  val_ratio: 0.2

seed: 41

sampling:
  split_method: random # rigid_split, random, uniform 블록 개수, class 별로 하여 train, val 나눔
  under_sampling: False # 각 블록 개수에서 train_target_sample_num, val_target_sample_num을 넘어갔을 때 undersampling 할지 여부
  
generating:
  folder_name: merged16 # 결과 저장 폴더 이름
  train_target_sample_num: 0 # 5000 -> class 당 사용하는 데이터 개수
  val_target_sample_num: 0 #1250 -> merge10 : 0
  auto_block_size: False # block size 자동 조정
  same_class_generate: 
    option: False # 합성 사용 여부
    ratio: 0 # not
    over_num: 2 # -> 해당 숫자 이상의 블록 개수부터 합성함
  background:
    option: True # -> background 사용 여부
    num: 100 # -> background 생성 개수
    existed_path: '' # -> background data가 이미 있어 만들 필요 없는 경우 사용
    val_existed_path: ''
    split_train_val: False # bool -> train과 valid의 배경을 다르게 할지 여부

augmentation:
  train_transform_option: False
  val_transform_option: True
  
make_test:
  make_test: True # test data도 현재 train, val 형식과 맞춰서 생성할지 여부
  test_folder_name: merged16 # test 파일 저장할 폴더 이름
    

